# Generated by Django 4.2 on 2024-09-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="Unknown", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="Unknown", max_length=20),
            preserve_default=False,
        ),
    ]
