# Generated by Django 4.2 on 2024-09-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_name_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="Self_introduction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="birthdate",
            field=models.DateField(default="1996-10-24"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
    ]
